# action.yml
name: 'auto-fmt'
description: 'Execute `terrafrom fmt` for edited .tf files.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ secrets.GITHUB_TOKEN }}
    - ${{ github.repository }}
    - ${{ github.base_ref }}
    - ${{ github.head_ref }}