# action.yml
name: 'auto-fmt'
description: 'Execute `terrafrom fmt` for edited .tf files.'
branding:
  icon: check-circle
  color: purple

inputs:
  token:
    default: ${{ github.token }}

  repository:
    default: ${{ github.repository }}

  base_ref:
    default: ${{ github.base_ref }}

  head_ref:
    default: ${{ github.head_ref }}

  triggering_actor:
    default: ${{ github.triggering_actor }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.base_ref }}
    - ${{ inputs.head_ref }}
    - ${{ inputs.triggering_actor }}