on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fmt:
    runs-on: ubuntu-latest
    name: auto-fmt
    steps:
      - uses: u-cto-devops/auto-fmt@v1.1.0
